### ISSUE TITLE
Keybinds does not work at all

### ISSUE THREAD

**Issue by NoobChester** [Leo40Git/ConflictInHarmony#1]
For some reason I could not use any keybind at all
Minecraft version: 1.16.1
Fabric version: 0.9.0+build.204
Mod version: v1.0.1 for 1.16.1

I did not get any log output when I click the keys, the only key that works is the ESC key (thankfully)

Any idea why would this happen?

**Comment by Leo40Git** [comment]
Apparently I somehow borked saving and loading keybinds (as #2 showed me)??? I have no idea how this happened.
